name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Roda todo dia Ã  meia-noite
  workflow_dispatch: # Permite rodar manualmente
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Adair-mbf
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
